// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/tim15/wiz/api/proto/daemon.proto

/*
Package daemon is a generated protocol buffer package.

It is generated from these files:
	github.com/tim15/wiz/api/proto/daemon.proto

It has these top-level messages:
	Version
	PackageList
	Status
	Empty
*/
package daemon

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import pkg "github.com/tim15/wiz/api/pkg"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Version struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *Version) Reset()                    { *m = Version{} }
func (m *Version) String() string            { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()               {}
func (*Version) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Version) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type PackageList struct {
	Packages []*pkg.Package `protobuf:"bytes,1,rep,name=packages" json:"packages,omitempty"`
}

func (m *PackageList) Reset()                    { *m = PackageList{} }
func (m *PackageList) String() string            { return proto.CompactTextString(m) }
func (*PackageList) ProtoMessage()               {}
func (*PackageList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PackageList) GetPackages() []*pkg.Package {
	if m != nil {
		return m.Packages
	}
	return nil
}

type Status struct {
	Status bool `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Status) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Version)(nil), "daemon.Version")
	proto.RegisterType((*PackageList)(nil), "daemon.PackageList")
	proto.RegisterType((*Status)(nil), "daemon.Status")
	proto.RegisterType((*Empty)(nil), "daemon.Empty")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Daemon service

type DaemonClient interface {
	GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Version, error)
	InstallPackages(ctx context.Context, in *PackageList, opts ...grpc.CallOption) (*Status, error)
	GetPackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PackageList, error)
}

type daemonClient struct {
	cc *grpc.ClientConn
}

func NewDaemonClient(cc *grpc.ClientConn) DaemonClient {
	return &daemonClient{cc}
}

func (c *daemonClient) GetVersion(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Version, error) {
	out := new(Version)
	err := grpc.Invoke(ctx, "/daemon.Daemon/GetVersion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) InstallPackages(ctx context.Context, in *PackageList, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/daemon.Daemon/InstallPackages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *daemonClient) GetPackages(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PackageList, error) {
	out := new(PackageList)
	err := grpc.Invoke(ctx, "/daemon.Daemon/GetPackages", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Daemon service

type DaemonServer interface {
	GetVersion(context.Context, *Empty) (*Version, error)
	InstallPackages(context.Context, *PackageList) (*Status, error)
	GetPackages(context.Context, *Empty) (*PackageList, error)
}

func RegisterDaemonServer(s *grpc.Server, srv DaemonServer) {
	s.RegisterService(&_Daemon_serviceDesc, srv)
}

func _Daemon_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.Daemon/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).GetVersion(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_InstallPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).InstallPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.Daemon/InstallPackages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).InstallPackages(ctx, req.(*PackageList))
	}
	return interceptor(ctx, in, info, handler)
}

func _Daemon_GetPackages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DaemonServer).GetPackages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/daemon.Daemon/GetPackages",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DaemonServer).GetPackages(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Daemon_serviceDesc = grpc.ServiceDesc{
	ServiceName: "daemon.Daemon",
	HandlerType: (*DaemonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Daemon_GetVersion_Handler,
		},
		{
			MethodName: "InstallPackages",
			Handler:    _Daemon_InstallPackages_Handler,
		},
		{
			MethodName: "GetPackages",
			Handler:    _Daemon_GetPackages_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/tim15/wiz/api/proto/daemon.proto",
}

func init() { proto.RegisterFile("github.com/tim15/wiz/api/proto/daemon.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x13, 0xc4, 0xa4, 0x4e, 0xd4, 0xc2, 0x0a, 0x12, 0x72, 0x31, 0xae, 0x97, 0x80, 0xb2,
	0xc1, 0x16, 0xd1, 0xb3, 0x28, 0x45, 0xf0, 0x20, 0x11, 0x3c, 0x78, 0xdb, 0xd6, 0x25, 0x2e, 0x6d,
	0xb2, 0x4b, 0x77, 0xaa, 0xe8, 0x17, 0xf2, 0x6b, 0x0a, 0xfb, 0xa7, 0x88, 0x28, 0xbd, 0xcd, 0xdb,
	0x99, 0xdf, 0xdb, 0x37, 0x03, 0xa7, 0xad, 0xc4, 0xd7, 0xd5, 0x94, 0xcd, 0x54, 0x57, 0xa3, 0xec,
	0xce, 0x2f, 0xea, 0x77, 0xf9, 0x59, 0x73, 0x2d, 0x6b, 0xbd, 0x54, 0xa8, 0xea, 0x17, 0x2e, 0x3a,
	0xd5, 0x33, 0x2b, 0x48, 0xe2, 0x54, 0x71, 0xb6, 0x01, 0xd2, 0x7c, 0x36, 0xe7, 0xad, 0x70, 0x14,
	0x3d, 0x81, 0xf4, 0x49, 0x2c, 0x8d, 0x54, 0x3d, 0xc9, 0x21, 0x7d, 0x73, 0x65, 0x1e, 0x97, 0x71,
	0xb5, 0xd3, 0x04, 0x49, 0x2f, 0x21, 0x7b, 0x70, 0xd4, 0xbd, 0x34, 0x48, 0x2a, 0x18, 0x78, 0x13,
	0x93, 0xc7, 0xe5, 0x56, 0x95, 0x8d, 0x76, 0x99, 0x9e, 0xb7, 0xcc, 0xcf, 0x34, 0xeb, 0x2e, 0x2d,
	0x21, 0x79, 0x44, 0x8e, 0x2b, 0x43, 0x0e, 0x21, 0x31, 0xb6, 0xb2, 0xde, 0x83, 0xc6, 0x2b, 0x9a,
	0xc2, 0xf6, 0x6d, 0xa7, 0xf1, 0x63, 0xf4, 0x15, 0x43, 0x72, 0x63, 0x37, 0x20, 0x0c, 0x60, 0x22,
	0x30, 0xc4, 0xda, 0x63, 0x7e, 0x4d, 0x3b, 0x57, 0x0c, 0x83, 0xf4, 0x7d, 0x1a, 0x91, 0x2b, 0x18,
	0xde, 0xf5, 0x06, 0xf9, 0x62, 0xe1, 0x13, 0x18, 0x72, 0x10, 0xa6, 0x7e, 0xe4, 0x2e, 0xf6, 0xc3,
	0xa3, 0xcb, 0x44, 0x23, 0x32, 0x86, 0x6c, 0x22, 0x70, 0x4d, 0xfd, 0xfa, 0xea, 0x2f, 0x13, 0x1a,
	0x5d, 0x1f, 0x3f, 0x1f, 0xfd, 0x7b, 0x62, 0x07, 0x4c, 0x13, 0x7b, 0xdc, 0xf1, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xe2, 0xd9, 0xb7, 0x8a, 0xc1, 0x01, 0x00, 0x00,
}
