// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// AddDataOKCode is the HTTP code returned for type AddDataOK
const AddDataOKCode int = 200

/*AddDataOK OK

swagger:response addDataOK
*/
type AddDataOK struct {

	/*
	  In: Body
	*/
	Payload *AddDataOKBody `json:"body,omitempty"`
}

// NewAddDataOK creates AddDataOK with default headers values
func NewAddDataOK() *AddDataOK {

	return &AddDataOK{}
}

// WithPayload adds the payload to the add data o k response
func (o *AddDataOK) WithPayload(payload *AddDataOKBody) *AddDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add data o k response
func (o *AddDataOK) SetPayload(payload *AddDataOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
