// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetProcessorHandlerFunc turns a function with the right signature into a get processor handler
type GetProcessorHandlerFunc func(GetProcessorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetProcessorHandlerFunc) Handle(params GetProcessorParams) middleware.Responder {
	return fn(params)
}

// GetProcessorHandler interface for that can handle valid get processor params
type GetProcessorHandler interface {
	Handle(GetProcessorParams) middleware.Responder
}

// NewGetProcessor creates a new http.Handler for the get processor operation
func NewGetProcessor(ctx *middleware.Context, handler GetProcessorHandler) *GetProcessor {
	return &GetProcessor{Context: ctx, Handler: handler}
}

/*GetProcessor swagger:route GET /processor/{id} Processors getProcessor

GetProcessor

*/
type GetProcessor struct {
	Context *middleware.Context
	Handler GetProcessorHandler
}

func (o *GetProcessor) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetProcessorParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
