// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/alexkreidler/wiz/models"
)

// GetAllRunsOKCode is the HTTP code returned for type GetAllRunsOK
const GetAllRunsOKCode int = 200

/*GetAllRunsOK OK

swagger:response getAllRunsOK
*/
type GetAllRunsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Run `json:"body,omitempty"`
}

// NewGetAllRunsOK creates GetAllRunsOK with default headers values
func NewGetAllRunsOK() *GetAllRunsOK {

	return &GetAllRunsOK{}
}

// WithPayload adds the payload to the get all runs o k response
func (o *GetAllRunsOK) WithPayload(payload []*models.Run) *GetAllRunsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all runs o k response
func (o *GetAllRunsOK) SetPayload(payload []*models.Run) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllRunsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Run, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
