// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllRunsHandlerFunc turns a function with the right signature into a get all runs handler
type GetAllRunsHandlerFunc func(GetAllRunsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllRunsHandlerFunc) Handle(params GetAllRunsParams) middleware.Responder {
	return fn(params)
}

// GetAllRunsHandler interface for that can handle valid get all runs params
type GetAllRunsHandler interface {
	Handle(GetAllRunsParams) middleware.Responder
}

// NewGetAllRuns creates a new http.Handler for the get all runs operation
func NewGetAllRuns(ctx *middleware.Context, handler GetAllRunsHandler) *GetAllRuns {
	return &GetAllRuns{Context: ctx, Handler: handler}
}

/*GetAllRuns swagger:route GET /processor/{id}/runs Processors getAllRuns

GetAllRuns

*/
type GetAllRuns struct {
	Context *middleware.Context
	Handler GetAllRunsHandler
}

func (o *GetAllRuns) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllRunsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
