// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetOutputChunkParams creates a new GetOutputChunkParams object
// no default values defined in spec.
func NewGetOutputChunkParams() GetOutputChunkParams {

	return GetOutputChunkParams{}
}

// GetOutputChunkParams contains all the bound params for the get output chunk operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetOutputChunk
type GetOutputChunkParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The output chunk ID to retrieve
	  Required: true
	  In: path
	*/
	ChunkID string
	/*The processor ID
	  Required: true
	  In: path
	*/
	ID string
	/*The run ID
	  Required: true
	  In: path
	*/
	RunID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetOutputChunkParams() beforehand.
func (o *GetOutputChunkParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rChunkID, rhkChunkID, _ := route.Params.GetOK("chunkID")
	if err := o.bindChunkID(rChunkID, rhkChunkID, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	rRunID, rhkRunID, _ := route.Params.GetOK("runID")
	if err := o.bindRunID(rRunID, rhkRunID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChunkID binds and validates parameter ChunkID from path.
func (o *GetOutputChunkParams) bindChunkID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ChunkID = raw

	return nil
}

// bindID binds and validates parameter ID from path.
func (o *GetOutputChunkParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.ID = raw

	return nil
}

// bindRunID binds and validates parameter RunID from path.
func (o *GetOutputChunkParams) bindRunID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.RunID = raw

	return nil
}
