// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetInputChunkOKCode is the HTTP code returned for type GetInputChunkOK
const GetInputChunkOKCode int = 200

/*GetInputChunkOK OK

swagger:response getInputChunkOK
*/
type GetInputChunkOK struct {

	/*
	  In: Body
	*/
	Payload *GetInputChunkOKBody `json:"body,omitempty"`
}

// NewGetInputChunkOK creates GetInputChunkOK with default headers values
func NewGetInputChunkOK() *GetInputChunkOK {

	return &GetInputChunkOK{}
}

// WithPayload adds the payload to the get input chunk o k response
func (o *GetInputChunkOK) WithPayload(payload *GetInputChunkOKBody) *GetInputChunkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get input chunk o k response
func (o *GetInputChunkOK) SetPayload(payload *GetInputChunkOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetInputChunkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
