// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetOutputChunkOKCode is the HTTP code returned for type GetOutputChunkOK
const GetOutputChunkOKCode int = 200

/*GetOutputChunkOK OK

swagger:response getOutputChunkOK
*/
type GetOutputChunkOK struct {

	/*
	  In: Body
	*/
	Payload *GetOutputChunkOKBody `json:"body,omitempty"`
}

// NewGetOutputChunkOK creates GetOutputChunkOK with default headers values
func NewGetOutputChunkOK() *GetOutputChunkOK {

	return &GetOutputChunkOK{}
}

// WithPayload adds the payload to the get output chunk o k response
func (o *GetOutputChunkOK) WithPayload(payload *GetOutputChunkOKBody) *GetOutputChunkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get output chunk o k response
func (o *GetOutputChunkOK) SetPayload(payload *GetOutputChunkOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetOutputChunkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
