// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetDataOKCode is the HTTP code returned for type GetDataOK
const GetDataOKCode int = 200

/*GetDataOK OK

swagger:response getDataOK
*/
type GetDataOK struct {

	/*
	  In: Body
	*/
	Payload *GetDataOKBody `json:"body,omitempty"`
}

// NewGetDataOK creates GetDataOK with default headers values
func NewGetDataOK() *GetDataOK {

	return &GetDataOK{}
}

// WithPayload adds the payload to the get data o k response
func (o *GetDataOK) WithPayload(payload *GetDataOKBody) *GetDataOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get data o k response
func (o *GetDataOK) SetPayload(payload *GetDataOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetDataOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
