// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"
)

// GetOutputChunkURL generates an URL for the get output chunk operation
type GetOutputChunkURL struct {
	ChunkID string
	ID      string
	RunID   string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetOutputChunkURL) WithBasePath(bp string) *GetOutputChunkURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetOutputChunkURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetOutputChunkURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/processor/{id}/run/{runID}/data/output/{chunkID}"

	chunkID := o.ChunkID
	if chunkID != "" {
		_path = strings.Replace(_path, "{chunkID}", chunkID, -1)
	} else {
		return nil, errors.New("chunkId is required on GetOutputChunkURL")
	}

	id := o.ID
	if id != "" {
		_path = strings.Replace(_path, "{id}", id, -1)
	} else {
		return nil, errors.New("id is required on GetOutputChunkURL")
	}

	runID := o.RunID
	if runID != "" {
		_path = strings.Replace(_path, "{runID}", runID, -1)
	} else {
		return nil, errors.New("runId is required on GetOutputChunkURL")
	}

	_basePath := o._basePath
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetOutputChunkURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetOutputChunkURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetOutputChunkURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetOutputChunkURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetOutputChunkURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetOutputChunkURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
