// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAllProcessorsHandlerFunc turns a function with the right signature into a get all processors handler
type GetAllProcessorsHandlerFunc func(GetAllProcessorsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAllProcessorsHandlerFunc) Handle(params GetAllProcessorsParams) middleware.Responder {
	return fn(params)
}

// GetAllProcessorsHandler interface for that can handle valid get all processors params
type GetAllProcessorsHandler interface {
	Handle(GetAllProcessorsParams) middleware.Responder
}

// NewGetAllProcessors creates a new http.Handler for the get all processors operation
func NewGetAllProcessors(ctx *middleware.Context, handler GetAllProcessorsHandler) *GetAllProcessors {
	return &GetAllProcessors{Context: ctx, Handler: handler}
}

/*GetAllProcessors swagger:route GET /processors Processors getAllProcessors

GetAllProcessors

*/
type GetAllProcessors struct {
	Context *middleware.Context
	Handler GetAllProcessorsHandler
}

func (o *GetAllProcessors) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAllProcessorsParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
