// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetProcessorOKCode is the HTTP code returned for type GetProcessorOK
const GetProcessorOKCode int = 200

/*GetProcessorOK OK

swagger:response getProcessorOK
*/
type GetProcessorOK struct {

	/*
	  In: Body
	*/
	Payload *GetProcessorOKBody `json:"body,omitempty"`
}

// NewGetProcessorOK creates GetProcessorOK with default headers values
func NewGetProcessorOK() *GetProcessorOK {

	return &GetProcessorOK{}
}

// WithPayload adds the payload to the get processor o k response
func (o *GetProcessorOK) WithPayload(payload *GetProcessorOKBody) *GetProcessorOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get processor o k response
func (o *GetProcessorOK) SetPayload(payload *GetProcessorOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetProcessorOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
