// Code generated by go-swagger; DO NOT EDIT.

package processors

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetRunOKCode is the HTTP code returned for type GetRunOK
const GetRunOKCode int = 200

/*GetRunOK OK

swagger:response getRunOK
*/
type GetRunOK struct {

	/*
	  In: Body
	*/
	Payload *GetRunOKBody `json:"body,omitempty"`
}

// NewGetRunOK creates GetRunOK with default headers values
func NewGetRunOK() *GetRunOK {

	return &GetRunOK{}
}

// WithPayload adds the payload to the get run o k response
func (o *GetRunOK) WithPayload(payload *GetRunOKBody) *GetRunOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get run o k response
func (o *GetRunOK) SetPayload(payload *GetRunOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRunOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
