// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Wiz Processor API
This document defines the Wiz Processor API as implemented using JSON over HTTP.


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
