// Code generated by protoc-gen-go. DO NOT EDIT.
// source: package.proto

/*
Package pkg is a generated protocol buffer package.

It is generated from these files:
	package.proto

It has these top-level messages:
	Package
*/
package pkg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Package_PackageType int32

const (
	Package_PROGRAM   Package_PackageType = 0
	Package_RUNTIME   Package_PackageType = 1
	Package_MODEL     Package_PackageType = 2
	Package_FRAMEWORK Package_PackageType = 3
)

var Package_PackageType_name = map[int32]string{
	0: "PROGRAM",
	1: "RUNTIME",
	2: "MODEL",
	3: "FRAMEWORK",
}
var Package_PackageType_value = map[string]int32{
	"PROGRAM":   0,
	"RUNTIME":   1,
	"MODEL":     2,
	"FRAMEWORK": 3,
}

func (x Package_PackageType) String() string {
	return proto.EnumName(Package_PackageType_name, int32(x))
}
func (Package_PackageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Package struct {
	Name         string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version      string                `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	Type         Package_PackageType   `protobuf:"varint,3,opt,name=type,enum=pkg.Package_PackageType" json:"type,omitempty"`
	Dependencies []*Package_Dependency `protobuf:"bytes,4,rep,name=dependencies" json:"dependencies,omitempty"`
	Info         *Package_MetaInfo     `protobuf:"bytes,5,opt,name=info" json:"info,omitempty"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Package) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Package) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Package) GetType() Package_PackageType {
	if m != nil {
		return m.Type
	}
	return Package_PROGRAM
}

func (m *Package) GetDependencies() []*Package_Dependency {
	if m != nil {
		return m.Dependencies
	}
	return nil
}

func (m *Package) GetInfo() *Package_MetaInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type Package_Dependency struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *Package_Dependency) Reset()                    { *m = Package_Dependency{} }
func (m *Package_Dependency) String() string            { return proto.CompactTextString(m) }
func (*Package_Dependency) ProtoMessage()               {}
func (*Package_Dependency) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Package_Dependency) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Package_Dependency) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type Package_MetaInfo struct {
	Author      string   `protobuf:"bytes,1,opt,name=author" json:"author,omitempty"`
	Repository  string   `protobuf:"bytes,2,opt,name=repository" json:"repository,omitempty"`
	Url         string   `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Description string   `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Keywords    []string `protobuf:"bytes,5,rep,name=keywords" json:"keywords,omitempty"`
}

func (m *Package_MetaInfo) Reset()                    { *m = Package_MetaInfo{} }
func (m *Package_MetaInfo) String() string            { return proto.CompactTextString(m) }
func (*Package_MetaInfo) ProtoMessage()               {}
func (*Package_MetaInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 1} }

func (m *Package_MetaInfo) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Package_MetaInfo) GetRepository() string {
	if m != nil {
		return m.Repository
	}
	return ""
}

func (m *Package_MetaInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Package_MetaInfo) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Package_MetaInfo) GetKeywords() []string {
	if m != nil {
		return m.Keywords
	}
	return nil
}

func init() {
	proto.RegisterType((*Package)(nil), "pkg.Package")
	proto.RegisterType((*Package_Dependency)(nil), "pkg.Package.Dependency")
	proto.RegisterType((*Package_MetaInfo)(nil), "pkg.Package.MetaInfo")
	proto.RegisterEnum("pkg.Package_PackageType", Package_PackageType_name, Package_PackageType_value)
}

func init() { proto.RegisterFile("package.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x14, 0x34, 0xdd, 0xf4, 0x23, 0x2f, 0x56, 0xc2, 0x03, 0x75, 0xe9, 0x41, 0x42, 0x4f, 0x11, 0xa4,
	0x87, 0x7a, 0xd3, 0x53, 0xa1, 0x55, 0x8a, 0xc6, 0x96, 0xa5, 0xe2, 0x39, 0x36, 0xaf, 0x35, 0x44,
	0xb3, 0xcb, 0x26, 0x55, 0xf2, 0x37, 0xfc, 0x87, 0xfe, 0x13, 0xe9, 0x9a, 0x68, 0x7b, 0xf4, 0xb4,
	0x6f, 0x66, 0x67, 0x66, 0xd9, 0x79, 0xd0, 0x55, 0xd1, 0x32, 0x8d, 0xd6, 0x34, 0x50, 0x5a, 0x16,
	0x12, 0x99, 0x4a, 0xd7, 0xfd, 0x2f, 0x06, 0xed, 0xf9, 0x0f, 0x8d, 0x08, 0x76, 0x16, 0xbd, 0x11,
	0xb7, 0x7c, 0x2b, 0x70, 0x84, 0x99, 0x91, 0x43, 0xfb, 0x9d, 0x74, 0x9e, 0xc8, 0x8c, 0x37, 0x0c,
	0x5d, 0x43, 0xbc, 0x00, 0xbb, 0x28, 0x15, 0x71, 0xe6, 0x5b, 0xc1, 0xd1, 0x90, 0x0f, 0x54, 0xba,
	0x1e, 0x54, 0x49, 0xf5, 0xb9, 0x28, 0x15, 0x09, 0xa3, 0xc2, 0x6b, 0x38, 0x8c, 0x49, 0x51, 0x16,
	0x53, 0xb6, 0x4c, 0x28, 0xe7, 0xb6, 0xcf, 0x02, 0x77, 0x78, 0xba, 0xe7, 0x1a, 0xd7, 0x82, 0x52,
	0xec, 0x89, 0xf1, 0x1c, 0xec, 0x24, 0x5b, 0x49, 0xde, 0xf4, 0xad, 0xc0, 0x1d, 0x1e, 0xef, 0x99,
	0x42, 0x2a, 0xa2, 0x69, 0xb6, 0x92, 0xc2, 0x48, 0x7a, 0x57, 0x00, 0x7f, 0x31, 0xff, 0xfb, 0x51,
	0xef, 0xd3, 0x82, 0x4e, 0x1d, 0x87, 0x27, 0xd0, 0x8a, 0x36, 0xc5, 0x8b, 0xd4, 0x95, 0xb9, 0x42,
	0x78, 0x06, 0xa0, 0x49, 0xc9, 0x3c, 0x29, 0xa4, 0x2e, 0xab, 0x84, 0x1d, 0x06, 0x3d, 0x60, 0x1b,
	0xfd, 0x6a, 0x5a, 0x71, 0xc4, 0x76, 0x44, 0x1f, 0xdc, 0x98, 0xf2, 0xa5, 0x4e, 0x54, 0xb1, 0x7d,
	0xd4, 0x36, 0x37, 0xbb, 0x14, 0xf6, 0xa0, 0x93, 0x52, 0xf9, 0x21, 0x75, 0x9c, 0xf3, 0xa6, 0xcf,
	0x02, 0x47, 0xfc, 0xe2, 0xfe, 0x08, 0xdc, 0x9d, 0x36, 0xd1, 0x85, 0xf6, 0x5c, 0xcc, 0x6e, 0xc5,
	0x28, 0xf4, 0x0e, 0xb6, 0x40, 0x3c, 0x3e, 0x2c, 0xa6, 0xe1, 0xc4, 0xb3, 0xd0, 0x81, 0x66, 0x38,
	0x1b, 0x4f, 0xee, 0xbd, 0x06, 0x76, 0xc1, 0xb9, 0x11, 0xa3, 0x70, 0xf2, 0x34, 0x13, 0x77, 0x1e,
	0x7b, 0x6e, 0x99, 0x7d, 0x5f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb3, 0xc3, 0xf3, 0x56, 0x00,
	0x02, 0x00, 0x00,
}
