// Code generated by capnpc-go. DO NOT EDIT.

package books

import (
	capnp "zombiezen.com/go/capnproto2"
	text "zombiezen.com/go/capnproto2/encoding/text"
	schemas "zombiezen.com/go/capnproto2/schemas"
)

type Book struct{ capnp.Struct }

// Book_TypeID is the unique identifier for the type Book.
const Book_TypeID = 0xe3881dd42a11f660

func NewBook(s *capnp.Segment) (Book, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Book{st}, err
}

func NewRootBook(s *capnp.Segment) (Book, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Book{st}, err
}

func ReadRootBook(msg *capnp.Message) (Book, error) {
	root, err := msg.RootPtr()
	return Book{root.Struct()}, err
}

func (s Book) String() string {
	str, _ := text.Marshal(0xe3881dd42a11f660, s.Struct)
	return str
}

func (s Book) Title() (string, error) {
	p, err := s.Struct.Ptr(0)
	return p.Text(), err
}

func (s Book) HasTitle() bool {
	p, err := s.Struct.Ptr(0)
	return p.IsValid() || err != nil
}

func (s Book) TitleBytes() ([]byte, error) {
	p, err := s.Struct.Ptr(0)
	return p.TextBytes(), err
}

func (s Book) SetTitle(v string) error {
	return s.Struct.SetText(0, v)
}

func (s Book) PageCount() int32 {
	return int32(s.Struct.Uint32(0))
}

func (s Book) SetPageCount(v int32) {
	s.Struct.SetUint32(0, uint32(v))
}

// Book_List is a list of Book.
type Book_List struct{ capnp.List }

// NewBook creates a new list of Book.
func NewBook_List(s *capnp.Segment, sz int32) (Book_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return Book_List{l}, err
}

func (s Book_List) At(i int) Book { return Book{s.List.Struct(i)} }

func (s Book_List) Set(i int, v Book) error { return s.List.SetStruct(i, v.Struct) }

func (s Book_List) String() string {
	str, _ := text.MarshalList(0xe3881dd42a11f660, s.List)
	return str
}

// Book_Promise is a wrapper for a Book promised by a client call.
type Book_Promise struct{ *capnp.Pipeline }

func (p Book_Promise) Struct() (Book, error) {
	s, err := p.Pipeline.Struct()
	return Book{s}, err
}

const schema_ef5a6e7f51007b47 = "x\xda\x120q`\x12d\x8dg`\x08dae\xfb" +
	"\x9f\xf0MP\xeb\x8al\xc7c\x86@1F\xc6\xdf\xee" +
	"\xd5\x81\xf5yQ\xefY\x19\xd9\x19\x18\x04Eo\x09*" +
	"\x82h\xd9r\x06\xc6\xff\xc9\x89\x05y\x05E\xf9%L" +
	"\xf9\xfaI\xf9\xf9\xd9\xc5z`\x01+\xa7|\xe6\xfc\xec" +
	"\x00F\xc6@\x0ef\x16\x06\x06\x16F\x06\x06AM#" +
	"\x06\x86@\x15f\xc6@\x03&FFF\x11F\x90\x98" +
	"n\x10\x03C\xa0\x0e3c\xa0\x05\x13\xa3|IfI" +
	"N*#\x0f\x03\x13#\x0f\x03\xe3\xff\x82\xc4\xf4T\xe7" +
	"\xfc\xd2<\x06\xc6\x12F\x16\x06&F\x16\x06F@\x00" +
	"\x00\x00\xff\xff\x88\xac\"\xf3"

func init() {
	schemas.Register(schema_ef5a6e7f51007b47,
		0xe3881dd42a11f660)
}
