package api

// Generated by https://quicktype.io

type Response struct {
	Data Data `json:"data"`
}

type Data struct {
	Type  string `json:"type"` 
	Value Value  `json:"value"`
}

type Value struct {
	Driver   string `json:"driver"`  
	Location string `json:"location"`
}

// Generated by https://quicktype.io

type Res struct {
	Data Data `json:"data"`
}

type Data struct {
	Type  string `json:"type"` 
	Value Value  `json:"value"`
}

type Value struct {
	Driver   string `json:"driver"`  
	Location string `json:"location"`
}
