// Code generated by go-enum
// DO NOT EDIT!

package api

import (
	"fmt"
)

const (
	// DataTypeRAW is a DataType of type RAW
	// raw generic data
	DataTypeRAW DataType = iota + 1
	// DataTypeFILESYSTEMREF is a DataType of type FILESYSTEM_REF
	// a reference to a file or folder accessible to the processor
	DataTypeFILESYSTEMREF
)

const _DataTypeName = "RAWFILESYSTEM_REF"

var _DataTypeMap = map[DataType]string{
	1: _DataTypeName[0:3],
	2: _DataTypeName[3:17],
}

// String implements the Stringer interface.
func (x DataType) String() string {
	if str, ok := _DataTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("DataType(%d)", x)
}

var _DataTypeValue = map[string]DataType{
	_DataTypeName[0:3]:  1,
	_DataTypeName[3:17]: 2,
}

// ParseDataType attempts to convert a string to a DataType
func ParseDataType(name string) (DataType, error) {
	if x, ok := _DataTypeValue[name]; ok {
		return x, nil
	}
	return DataType(0), fmt.Errorf("%s is not a valid DataType", name)
}

// MarshalText implements the text marshaller method
func (x DataType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *DataType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseDataType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
